services:
  - type: web
    name: tax-calculation-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    rootDir: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 